<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\LocalAI.Core\LocalAI.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Whisper.net" />
    <PackageReference Include="Whisper.net.Runtime" />
    <PackageReference Include="Whisper.net.Runtime.Cuda.Windows" />
    <PackageReference Include="org.k2fsa.sherpa.onnx" />
  </ItemGroup>
</Project>
