<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\LocalAI.Core\LocalAI.Core.csproj" />
    <ProjectReference Include="..\LocalAI.LLM\LocalAI.LLM.csproj" />
    <ProjectReference Include="..\LocalAI.Memory\LocalAI.Memory.csproj" />
    <ProjectReference Include="..\LocalAI.Speech\LocalAI.Speech.csproj" />
    <ProjectReference Include="..\LocalAI.Audio\LocalAI.Audio.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>
</Project>
